### ISSUE TITLE
After automatic reload of the markdown preview the workbench considers the markdown preview editor the active editor

### ISSUE THREAD

**Issue by kieferrm** [kieferrm/vscode-markdown#8]
1) open a .md file
2) use Open Preview to the Side
3) make a change to the .md file again
4) save
-> Preview updates
5) make another change
-> the file is dirty but Save is disabled

**Comment by rebornix** [comment]
Put more information here, after we invoke the markdown preview panel from extension, the original editor is no longer the activeEditor anymore. This also happens when we invoke the built-in markdown preview panel.

![image](https://cloud.githubusercontent.com/assets/876920/15232565/0734fc66-1857-11e6-8233-1c72304e96c5.png)

From above image, you can see the title of left document is grayed out and has no split button on the top right corner. It's totally the same no matter it's a built-in markdown functionality or our extension. Besides, the cursor is still blinking inside the left document as we don't move it.

Here is the problem. If we are previewing markdown with built-in one, we can't type anything into left document even though the cursor is in it. But with our extension, you can type in anything and makes it dirty. VS Code has some inconsistency of determining whether it's inactive/read only or not.

**Comment by kieferrm** [comment]
The issue was that the web view used to set the focus on the contentDocument rather than the contentWindow. This is fixed.
